server:
  port: 9003

spring:
  application:
    name: demo
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/znpb?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: password

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.bph.commons.pojo

eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka





